config/routes.rb
Rails.application.routes.draw do
  
  root 'reports#index'

  get "report", to: "reports#report"

  resources :reports
  resources :routes
  resources :reservations
  
end

app/models/reservation.rb
class Reservation < ApplicationRecord
	has_many :bookings, dependent: :destroy
	has_many :tickets, dependent: :destroy
	belongs_to :route

	def Reservation.res_create(route)
		
		number_of_seats = 35

		travel_date = Date.today
		for i in 1..10 do
			travel_date = travel_date + 1
			origin = route.origin
			destination = route.destination
			number_of_seats = route.number_of_seats
			departure_time = route.departure_time
			arrival_time = route.arrival_time
			duration = route.duration
		res = 	Reservation.create(travel_date: travel_date, number_of_seats: number_of_seats, origin: origin,
						destination: destination, departure_time: departure_time, arrival_time: arrival_time,
						duration: duration, route_id: route.id)
		
		Booking.booking_create(res,route)
		end
	end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    
    travel_date = params[:reservation][:travel_date]
    travel_date = Date.strptime(travel_date, '%m/%d/%Y')
    route = Route.find(params[:reservation][:route_id])

    @reservation = Reservation.new(travel_date: travel_date,number_of_seats: route.number_of_seats,
      origin: route.origin, destination: route.destination, departure_time: route.departure_time,
      arrival_time: route.arrival_time, duration: route.duration, route_id:route.id)

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= form_with(model: reservation, local: true, class: 'form-horizontal') do |form| %>
  <% if reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <br>

    <div class="form-group">
        <%= form.label 'Travel Date:', class: "col-sm-2 control-label" %>
        <div class='input-group date col-sm-8' id='datepicker'>             
          <%= form.text_field :travel_date, class: 'form-control', placeholder: 'Service Number' %>
          <span class="input-group-addon">
          <span class="glyphicon glyphicon-calendar"></span>
          </span>
        </div>
    </div>
  

  <div class="form-group">
    <%= form.label 'Route:', class: "col-sm-2 control-label" %>
    <div class="input-group col-sm-8">
      <%= form.collection_select(:route_id, Route.order(:route_name), :id, :route_name, {prompt: true}, {class: 'form-control', required: "required"})%>
    </div>    
  </div>


  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= form.submit class: 'btn btn-success' %>
    </div>
  </div>

<% end %>


<script>
  $(document).ready(function(){
    $('#datepicker').datepicker();
  });
</script>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h1 >Reservations</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Travel date</th>
      <th>Number of seats</th>
      <th>Origin</th>
      <th>Destination</th>
      <th>Departure time</th>
      <th>Arrival time</th>
      <th>Duration</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.travel_date %></td>
        <td><%= reservation.number_of_seats %></td>
        <td><%= reservation.origin %></td>
        <td><%= reservation.destination %></td>
        <td><%= reservation.departure_time.to_s(:time) %></td>
        <td><%= reservation.arrival_time.to_s(:time) %></td>
        <td><%= reservation.duration %></td>
        <td><%= link_to 'Show', reservation %></td>
        <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
        <td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reservation', new_reservation_path %>
</div>

app/views/reservations/new.html.erb
<div class="container">
<h1 style="text-align: center">New Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Back', reservations_path %>
</div>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Travel date:</strong>
  <%= @reservation.travel_date %>
</p>

<p>
  <strong>Number of seats:</strong>
  <%= @reservation.number_of_seats %>
</p>

<p>
  <strong>Origin:</strong>
  <%= @reservation.origin %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @reservation.destination %>
</p>

<p>
  <strong>Departure time:</strong>
  <%= @reservation.departure_time %>
</p>

<p>
  <strong>Arrival time:</strong>
  <%= @reservation.arrival_time %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @reservation.duration %>
</p>

<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>