config/routes.rb
Rails.application.routes.draw do
  
  root 'reports#index'

  get "report", to: "reports#report"

  resources :reports
  resources :routes
  resources :reservations
  
end

app/models/route.rb
class Route < ApplicationRecord
	has_many :reservations, dependent: :destroy
	has_many :bookings, dependent: :destroy

	def Route.create_route
		service = "TS"
		city_names = City.pluck('city_name')
		for i in 1..4 do

			arr = city_names.sample(2)
			origin = arr[0]
			destination = arr[1]

			service_no = service + "00#{i}"

			number_seat = 35

			departure_time = "06:00".to_time + i.hour

			duration = (6..12).to_a.sample

			arrival_time = departure_time + duration.hour

			route_name = "#{origin[0...3]}-#{destination[0...3]}"

			route = Route.create(route_name: route_name, service_number: service_no, origin: origin,
			destination: destination, number_of_seats: number_seat, departure_time: departure_time, arrival_time: arrival_time, duration: duration) 
			
			Reservation.res_create(route)

		end
	end
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :set_route, only: [:show, :edit, :update, :destroy]

  # GET /routes
  # GET /routes.json
  def index
    @routes = Route.all
  end

  # GET /routes/1
  # GET /routes/1.json
  def show
  end

  # GET /routes/new
  def new
    @route = Route.new
  end

  # GET /routes/1/edit
  def edit
  end

  # POST /routes
  # POST /routes.json
  def create
    if params[:route][:origin] != params[:route][:destination]
    route_name = params[:route][:origin][0..2].upcase + "-" + params[:route][:destination][0..2].upcase
  
    @route = Route.new(route_params)
    @route.route_name = route_name

    respond_to do |format|

      if @route.save
        format.html { redirect_to @route, notice: 'Route was successfully created.' }
        format.json { render :show, status: :created, location: @route }
      else
        format.html { render :new }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end

    else
      flash[:error] = "Origin and Destination cant be same"
      redirect_to new_route_path
    end

  end

  # PATCH/PUT /routes/1
  # PATCH/PUT /routes/1.json
  def update
    respond_to do |format|
      if @route.update(route_params)
        format.html { redirect_to @route, notice: 'Route was successfully updated.' }
        format.json { render :show, status: :ok, location: @route }
      else
        format.html { render :edit }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /routes/1
  # DELETE /routes/1.json
  def destroy
    @route.destroy
    respond_to do |format|
      format.html { redirect_to routes_url, notice: 'Route was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_route
      @route = Route.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def route_params
      params.require(:route).permit(:service_number,:number_of_seats, :origin, :destination, :departure_time, :arrival_time, :duration)
    end
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/views/routes/_form.html.erb
<%= form_with(model: route, local: true, class: 'form-horizontal') do |form| %>
<% if flash.any? %>
  <% flash.each do |error,message| %>
  <blockquote style="background-color: #f25050">
  <p><%= message %></p>
  </blockquote>

  
  <% end %>
<% end %>


  <div class="form-group">
    <%= form.label 'Service Number:', class: "col-sm-2 control-label" %>
    <div class="col-sm-8">
      <%= form.text_field :service_number, class: "form-control", placeholder: 'Service Number' %>
    </div>    
    <span class="error" style = "font-size: 13px; line-height: 3">e.g. TS001,TS002. </span>
  </div>
  <div class="form-group">
    <%= form.label 'Number Of Seats:', class: "col-sm-2 control-label" %>
    <div class="col-sm-8">
      <%= form.number_field :number_of_seats, class: "form-control", placeholder: 'Number Of Seats' %>
    </div>    
  </div>

  <div class="form-group">
    <%= form.label 'Origin:', class: "col-sm-2 control-label" %>
    <div class="col-sm-8">
      <%= form.collection_select(:origin, City.order(:city_name), :city_name, :city_name, {prompt: true}, {class: 'form-control col-md-10', required: "required"})%>
    </div>    
  </div>

  <div class="form-group">
    <%= form.label 'Destination:', class: "col-sm-2 control-label" %>
    <div class="col-sm-8">
      <%= form.collection_select(:destination, City.order(:city_name), :city_name, :city_name, {prompt: true}, {class: 'form-control col-md-10', required: "required"})%>
    </div>    
  </div>

  <div class="form-group">
    <%= form.label 'Departure Time:', class: "col-sm-2 control-label" %>
    <div class="col-sm-8">
      <%= form.time_select :departure_time, class: "form-control", placeholder: 'Departure Time' %>
    </div>    
  </div>

  <div class="form-group">
    <%= form.label 'Arrival Time:', class: "col-sm-2 control-label" %>
    <div class="col-sm-8">
      <%= form.time_select :arrival_time, class: "form-control", placeholder: 'Arrival Time' %>
    </div>    
  </div>

  <div class="form-group">
    <%= form.label 'Duration:', class: "col-sm-2 control-label" %>
    <div class="col-sm-8">
      <%= form.text_field :duration, class: "form-control", placeholder: 'Duration' %>
    </div>    
  </div>

  
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= form.submit class: 'btn btn-success' %>
    </div>
  </div>

  

<% end %>

app/views/routes/edit.html.erb
<h1>Editing Route</h1>

<%= render 'form', route: @route %>

<%= link_to 'Show', @route %> |
<%= link_to 'Back', routes_path %>

app/views/routes/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h1>Routes</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Route Name</th>
      <th>Number of seats</th>
      <th>Origin</th>
      <th>Destination</th>
      <th>Departure time</th>
      <th>Arrival time</th>
      <th>Duration</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @routes.each do |route| %>
      <tr>
        <td><%= route.route_name %></td>
        <td><%= route.number_of_seats %></td>
        <td><%= route.origin %></td>
        <td><%= route.destination %></td>
        <td><%= route.departure_time.to_s(:time)%></td>
        <td><%= route.arrival_time.to_s(:time) %></td>
        <td><%= route.duration %></td>
        <td><%= link_to 'Show', route %></td>
        <td><%= link_to 'Edit', edit_route_path(route) %></td>
        <td><%= link_to 'Destroy', route, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'New Route', new_route_path %>
</div>

app/views/routes/new.html.erb
 <div class="container">


<h1 style="text-align: center">Create New Route</h1>
<br>

<%= render 'form', route: @route %>

<%= link_to 'Back', routes_path %>

</div>

app/views/routes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number of seats:</strong>
  <%= @route.number_of_seats %>
</p>

<p>
  <strong>Origin:</strong>
  <%= @route.origin %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @route.destination %>
</p>

<p>
  <strong>Departure time:</strong>
  <%= @route.departure_time %>
</p>

<p>
  <strong>Arrival time:</strong>
  <%= @route.arrival_time %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @route.duration %>
</p>

<%= link_to 'Edit', edit_route_path(@route) %> |
<%= link_to 'Back', routes_path %>