config/routes.rb
Rails.application.routes.draw do
  
  root 'reports#index'

  get "report", to: "reports#report"

  resources :reports
  resources :routes
  resources :reservations
  
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index

     respond_to do |format|
       format.html
       format.csv { render text: Ticket.to_csv }
     end

  end

  def new

  end

  def report 

  	from_date = params['from_date']
  	to_date = params['to_date']  
    date_type = params['date_type']

    tickets = Ticket.joins(:user).select("pnr_number,passenger_name,sum(base_fare) as base_fare,sum(base_fare + base_fare*gst/100) as total_amount, gst,
        GROUP_CONCAT(tickets.seat_number) as seat_number, GROUP_CONCAT(IF(tickets.is_cancelled = true, tickets.seat_number, null))as cancelled_seat,sum(cancelled_fare) as cancelled_fare,
        sum(refund_amount) as refund_amount, SUM(net_fare)as net_fare, tickets.email, tickets.age,travel_date,issue_date,booking_id,user_id")

  	if(date_type == "issue_date")
  		 

      @bookings = tickets.where("issue_date BETWEEN ? AND ?", from_date, to_date).group(:booking_id).paginate(page: params[:page], per_page: 10)



       respond_to do |format|
          format.js { render :layout => false }
       end
     
    elsif(date_type == "travel_date")

       @bookings = tickets.where("travel_date BETWEEN ? AND ?", from_date, to_date).group(:booking_id).paginate(page: params[:page], per_page: 10)


      
        respond_to do |format|
          format.js { render :layout => false }
       end

    end
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_report.html.erb
<div class="container">
  
<table class="table table-striped" border="1 px">
  <thead>
    <tr style="color: white" class="t_header">
      <th>S.No.</th>
      <th>PNR NUMBER</th>
      <th>SEAT NUMBERS</th>
      <th>NAME</th>
      <th>EMAIL</th>
      <th>AGE</th>      
      <th>TRAVEL DATE</th>
      <th>ISSUE DATE</th>
      <th>BASE FARE</th>
      <th>GST%</th>
      <th>Total Amount</th>
      <th style="color: red ">CANCELLED TICKETS</th>
      <th style="color: red">CANCELATION AMOUNT</th>
      <th style="color: red">REFUND AMOUNT</th>
      <th>Net Fare</th>
    </tr>
  </thead>
 
  <tbody>
    <% @bookings.each_with_index do |booking,index| %>
      <tr>
        <td><%= index+1 %></td>
      	<td><%= booking.pnr_number %></td>
      	<td><%= booking.seat_number %></td>      	
        <td><%= booking.passenger_name %></td>
        <td><%= booking.email %></td>
        <td><%= booking.age %></td>
        <td><%= booking.travel_date %></td>
        <td><%= booking.issue_date %></td>
        <td><%= booking.base_fare %></td>
        <td><%= booking.gst %></td>
        <td><%= booking.total_amount.ceil(2) %></td>
        <td><%= booking.cancelled_seat %></td>
        <td><%= booking.cancelled_fare.ceil(2) %></td>
        <td><%= booking.refund_amount.ceil(2) %></td>
        <td><%= booking.net_fare.ceil(2) %></td>

       </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= will_paginate @bookings, renderer: BootstrapPagination::Rails %>
</div>


<div>
    
</div>

app/views/reports/index.html.erb
<h1>Reports#index</h1>
<p>Find me in app/views/reports/index.html.erb</p>

<%= link_to 'Find Reports', new_report_path %>

app/views/reports/new.html.erb
<head>
	<link href="https://fonts.googleapis.com/css?family=ZCOOL+XiaoWei&display=swap" rel="stylesheet">
<style type="text/css">
	body{
		background: #e2e2e2;
		font-family: 'ZCOOL XiaoWei', serif;
	}
</style>
</head>
<body>
<div class="signup-form">
    	<%= form_with(url: report_path, method: :get, remote: true) do |form| %>
		<div class="form-header">
			<h2>Booking Reports</h2>
			
		</div>

		<div class="form-group">
			<label>From Date</label>
            <div class='input-group date' id='datetimepicker6'>            	
                <%= form.text_field :from_date, class: 'form-control', data: { date_format: 'YYYY-MM-DD' } %>
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>
        </div>


        <div class="form-group">
        	<label>To Date</label>
            <div class='input-group date' id='datetimepicker7'>
            	<%= form.text_field :to_date, class: 'form-control', data: { date_format: 'YYYY-MM-DD'} %>
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>
        </div>

        <div class="radio radio-info">
	
			<%= form.radio_button :date_type, 'issue_date', :checked => true  %><label>Issue Date</label>
			
			
        </div>
		<div class="radio radio-info">
			<%= form.radio_button :date_type, 'travel_date' %><label>Travel Date</label>	
        </div>
        
		<div class="form-group">
			<%= form.submit "Run Reports", class: 'btn btn-primary btn-block btn-lg' %>
		</div>	
		<% end %>
	</div>



	<div id="fetch_report"> </div>
	<script>
	   $(function(){
	     $('.pagination a').attr('data-remote', 'true')
	   });

    $(function () {
        $('#datetimepicker6').datetimepicker();
        $('#datetimepicker7').datetimepicker({
            useCurrent: false 
        });
        $("#datetimepicker6").on("dp.change", function (e) {
            $('#datetimepicker7').data("DateTimePicker").minDate(e.date);
        });
        $("#datetimepicker7").on("dp.change", function (e) {
            $('#datetimepicker6').data("DateTimePicker").maxDate(e.date);
        });
    });
</script>
	
</body>

app/views/reports/report.js.erb
$("#fetch_report").html("<%= escape_javascript(render partial: 'reports/report') %>");	
$('.pagination a').attr('data-remote', 'true');